'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import Protected from '../../components/Protected';
import ProfileNav from '../../components/ProfileNav';
import { api, relativeTime } from '../../lib/api';

export default function ProfilePage(){const [points,setPoints]=useState([]);const [feedings,setFeedings]=useState([]);const [error,setError]=useState('');useEffect(()=>{Promise.all([api('/api/profile/points'),api('/api/profile/feedings')]).then(([p,f])=>{setPoints(p);setFeedings(f)}).catch(e=>setError(e.message))},[]);return <Protected><main className="page"><div className="pageTitle"><div><span className="eyebrow">บัญชีของฉัน</span><h1>กิจกรรมของฉัน</h1></div></div>{error&&<div className="errorBox">{error}</div>}<div className="profileGrid"><ProfileNav/><div><section className="card"><h3>ภาพรวมการช่วยเหลือ</h3><div className="stats"><div className="stat"><span>จุดที่สร้าง</span><strong>{points.length}</strong></div><div className="stat"><span>ครั้งที่ให้อาหาร</span><strong>{feedings.length}</strong></div><div className="stat"><span>กิจกรรมรวม</span><strong>{points.length+feedings.length}</strong></div></div></section><section className="card"><h3>จุดล่าสุด</h3>{points.slice(0,3).map(p=><div className="listRow" key={p.id}><div className="listIcon">{p.animalType==='DOG'?'🐶':p.animalType==='CAT'?'🐱':'🐾'}</div><div><strong>สัตว์จรจัดประมาณ {p.estimatedCount} ตัว</strong><div><span className="chip">{p.animalType}</span><span className="chip">{p.status}</span></div><small className="muted">อัปเดต {relativeTime(p.updatedAt)}</small></div><Link className="button" href={`/points/${p.id}`}>ดู</Link></div>)}{!points.length&&<div className="empty">ยังไม่ได้สร้างจุด</div>}</section><section className="card"><h3>การให้อาหารล่าสุด</h3>{feedings.slice(0,3).map(f=><div className="historyItem" key={f.id}><strong>{relativeTime(f.fedAt)}</strong><br/><small>{f.point?.animalType} · {f.note||'ให้อาหารแล้ว'}</small></div>)}{!feedings.length&&<div className="empty">ยังไม่มีประวัติการให้อาหาร</div>}</section></div></div></main></Protected>}
