'use client';

import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import { api, assetUrl, relativeTime } from '../../../lib/api';
import { useAuth } from '../../../lib/auth-context';

export default function PointDetailPage(){
  const {id}=useParams();const router=useRouter();const {user}=useAuth();
  const [point,setPoint]=useState(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [note,setNote]=useState('');const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setPoint(await api(`/api/points/${id}`));}catch(err){setError(err.message);}finally{setLoading(false)}},[id]);
  useEffect(()=>{load()},[load]);
  async function feed(){if(!user)return router.push(`/login?next=/points/${id}`);setBusy('feed');setError('');setMessage('');try{await api(`/api/points/${id}/feedings`,{method:'POST',body:JSON.stringify({note:note||undefined})});setNote('');setMessage('บันทึกการให้อาหารแล้ว');await load();}catch(err){setError(err.message);}finally{setBusy('')}}
  async function report(type){if(!user)return router.push(`/login?next=/points/${id}`);setBusy(type);setError('');setMessage('');try{await api(`/api/points/${id}/reports`,{method:'POST',body:JSON.stringify({type})});setMessage(type==='STILL_HERE'?'ยืนยันว่าพบสัตว์อยู่แล้ว':'บันทึกว่าไม่พบสัตว์แล้ว');await load();}catch(err){setError(err.message);}finally{setBusy('')}}
  if(loading)return <main className="centerState">กำลังโหลดรายละเอียด...</main>;
  if(error&&!point)return <main className="page narrow"><div className="errorBox">{error}</div><Link href="/" className="button">← กลับแผนที่</Link></main>;
  if(!point)return null;
  const photo=assetUrl(point.images?.[0]?.imageUrl);const animal=point.animalType==='DOG'?'สุนัข':point.animalType==='CAT'?'แมว':'สัตว์อื่น ๆ';
  return <main className="page"><div className="pageTitle"><div><span className="eyebrow">รายละเอียดจุด</span><h1>{animal}จรจัด</h1><p>รายงานโดย {point.createdBy?.name||'ผู้ใช้ PawFeed'}</p></div><Link href="/" className="button">← กลับแผนที่</Link></div>{error&&<div className="errorBox">{error}</div>}{message&&<div className="successBox">{message}</div>}<section className="card detailGrid"><div>{photo?<img className="imageHero" src={photo} alt="รูปสัตว์จรจัด"/>:<div className="imageFallback"><span>ไม่มีรูปภาพ</span></div>}</div><div><span className="eyebrow">พบล่าสุด {relativeTime(point.lastSeenAt)}</span><h2 className="detailCount">ประมาณ {point.estimatedCount} ตัว</h2><p className="muted">{point.description}</p><div className="metaGrid"><div className="metaItem"><strong>ประเภท</strong>{point.animalType}</div><div className="metaItem"><strong>มักพบ</strong>{point.usualTime||'ไม่ระบุ'}</div><div className="metaItem"><strong>ให้อาหารล่าสุด</strong>{relativeTime(point.latestFeedingAt)}</div><div className="metaItem"><strong>สถานะ</strong>{point.status}</div></div><Link href={`/points/${id}/navigate`} className="button primary block detailNavigate">นำทางใน PawFeed</Link></div></section><section className="card"><h3>บันทึกการให้อาหาร</h3><p className="muted">ข้อมูลเวลาล่าสุดช่วยให้คนอื่นตัดสินใจก่อนเดินทางมา</p><div className="field"><label>หมายเหตุ (ไม่บังคับ)</label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="เช่น ให้อาหารเม็ดและเติมน้ำแล้ว"/></div><div className="formActions formActionsStart"><button className="button primary" disabled={busy==='feed'} onClick={feed}>{busy==='feed'?'กำลังบันทึก...':'ฉันให้อาหารแล้ว'}</button></div></section><section className="card"><h3>ประวัติการให้อาหาร</h3>{point.feedings?.length?point.feedings.map(item=><div className="historyItem" key={item.id}><strong>{relativeTime(item.fedAt)} · {item.user?.name||'ผู้ใช้'}</strong>{item.note&&<><br/><small>{item.note}</small></>}</div>):<div className="empty">ยังไม่มีประวัติการให้อาหาร</div>}</section><section className="card"><h3>ช่วยยืนยันข้อมูลจุดนี้</h3><p className="muted">การยืนยันช่วยให้ข้อมูลบนแผนที่เป็นปัจจุบัน โดย NOT_FOUND จะยังไม่ปิดจุดอัตโนมัติใน v1</p><div className="sectionActions"><button className="button soft" disabled={!!busy} onClick={()=>report('STILL_HERE')}>ยังพบสัตว์อยู่</button><button className="button danger" disabled={!!busy} onClick={()=>report('NOT_FOUND')}>ไม่พบแล้ว</button></div></section></main>;
}
