'use client';

import dynamic from 'next/dynamic';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import Protected from '../../../components/Protected';
import { api } from '../../../lib/api';

const MapPicker=dynamic(()=>import('../../../components/MapPicker'),{ssr:false});

export default function CreatePointPage(){
  const router=useRouter();
  const [form,setForm]=useState({animalType:'DOG',estimatedCount:'1',description:'',latitude:13.7291,longitude:100.7789,usualTime:''});
  const [image,setImage]=useState(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  function position(){if(!navigator.geolocation)return setError('Browser นี้ไม่รองรับตำแหน่ง');navigator.geolocation.getCurrentPosition(({coords})=>setForm(v=>({...v,latitude:coords.latitude,longitude:coords.longitude})),()=>setError('ไม่ได้รับสิทธิ์ตำแหน่ง คุณยังเลือกตำแหน่งบนแผนที่เองได้'));}
  async function submit(e){e.preventDefault();setError('');if(!image)return setError('กรุณาเพิ่มรูปอย่างน้อย 1 รูป');setLoading(true);try{const body=new FormData();Object.entries(form).forEach(([k,v])=>{if(v!==''&&v!=null)body.append(k,String(v))});body.append('image',image);const point=await api('/api/points',{method:'POST',body});router.push(`/points/${point.id}`);}catch(err){setError(err.message);}finally{setLoading(false)}}
  return <Protected><main className="page"><div className="pageTitle"><div><span className="eyebrow">สร้างหมุดใหม่</span><h1>เพิ่มจุดสัตว์จรจัด</h1><p>เลือกตำแหน่ง เพิ่มรูป และข้อมูลที่ช่วยให้คนอื่นค้นพบจุดนี้ได้</p></div></div>{error&&<div className="errorBox">{error}</div>}<form onSubmit={submit}><section className="card"><h3>1 · เลือกตำแหน่ง</h3><MapPicker value={{latitude:Number(form.latitude),longitude:Number(form.longitude)}} onChange={v=>setForm(f=>({...f,...v}))}/><div className="formGrid formGridSpaced"><div className="field"><label>Latitude</label><input type="number" step="any" min="-90" max="90" required value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/></div><div className="field"><label>Longitude</label><input type="number" step="any" min="-180" max="180" required value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/></div></div><div className="formActions"><button type="button" className="button soft" onClick={position}>ใช้ตำแหน่งปัจจุบัน</button></div></section><section className="card"><h3>2 · เพิ่มรูปสัตว์หรือบริเวณที่พบ</h3><label className="uploadBox"><div><span className="uploadSymbol" aria-hidden="true">IMG</span><strong>{image?image.name:'เลือกรูปภาพ'}</strong><br/><small>JPEG, PNG หรือ WebP · สูงสุดตามค่าที่ Backend กำหนด</small></div><input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setImage(e.target.files?.[0]||null)}/></label></section><section className="card"><h3>3 · รายละเอียดสัตว์</h3><div className="formGrid"><div className="field"><label>ประเภทสัตว์ *</label><select value={form.animalType} onChange={e=>setForm({...form,animalType:e.target.value})}><option value="DOG">สุนัข</option><option value="CAT">แมว</option><option value="OTHER">อื่น ๆ</option></select></div><div className="field"><label>จำนวนโดยประมาณ *</label><input type="number" min="1" required value={form.estimatedCount} onChange={e=>setForm({...form,estimatedCount:e.target.value})}/></div><div className="field full"><label>คำอธิบาย *</label><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="ลักษณะสัตว์ จุดสังเกต หรือข้อมูลที่ช่วยหาเจอ"/></div><div className="field full"><label>ช่วงเวลาที่มักพบ</label><input value={form.usualTime} onChange={e=>setForm({...form,usualTime:e.target.value})} placeholder="เช่น 17:00 - 20:00"/></div></div></section><div className="formActions"><button type="button" className="button" onClick={()=>router.push('/')}>ยกเลิก</button><button className="button primary" disabled={loading}>{loading?'กำลังสร้างจุด...':'สร้างจุดบนแผนที่'}</button></div></form></main></Protected>;
}
